job_trends:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: admin
      password: admin123
      dbname: job_trends
      schema: analytics
      threads: 4